enum StorageKey {
  dark,
  language,
  username,
  password,
  address,
  windowState,
  enableWindowState,
  enableSystemTray,
  rootPathServer,
  autoLoginAfterDeploy,
  temporaryDirectory,
  autoScriptList,
  autoDeploy,
}